copy balans.prg balans_1.prg
type vars.prg    >> balans_1.prg
type parol.prg   >> balans_1.prg
type inp.prg     >> balans_1.prg
type exprec.prg  >> balans_1.prg
type protoc.prg  >> balans_1.prg
type shablon.prg >> balans_1.prg
type quan.prg    >> balans_1.prg
type dict.prg    >> balans_1.prg
type come.prg    >> balans_1.prg
type raschet.prg >> balans_1.prg
type division.prg>> balans_1.prg
type docum.prg   >> balans_1.prg
type menu.prg    >> balans_1.prg
type func.prg    >> balans_1.prg
type inpmon.prg  >> balans_1.prg
type otchet.prg  >> balans_1.prg
type print.prg   >> balans_1.prg
type printo.prg  >> balans_1.prg
type printr.prg  >> balans_1.prg
type kassa.prg   >> balans_1.prg
type spravka.prg >> balans_1.prg
type tunes.prg   >> balans_1.prg
type tunesin.prg >> balans_1.prg
type tunelist.prg>> balans_1.prg
type arhivs.prg  >> balans_1.prg
type musor.prg   >> balans_1.prg
type title.prg   >> balans_1.prg
clipper balans_1 /M/Q/L
rtlink FI balans_1 OUT balans LIB clipper,extend,mcl
del balans_1.*
